pipeline:
  name: PipelineSampleDotNetApp
  identifier: PipelineSampleDotNetApp
  projectIdentifier: SampleProject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Vikas_Github_Account
        repoName: SampleDotNetApp
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessnadeem
              namespace: harness-delegate-ng
              automountServiceAccountToken: false
              nodeSelector: {}
              os: Windows
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone
                  identifier: GitClone
                  spec:
                    connectorRef: Vikas_Github_Account
                    repoName: SampleDotNetApp
                    build:
                      type: branch
                      spec:
                        branch: master
